### ISSUE TITLE
how to load clojureism and some examples

### ISSUE THREAD

**Issue by ram535** [shegeley/clojureism#1]
Could you add section in the readme where shows how to load this library and also add some examples?
Thanks.

**Comment by shegeley** [comment]
The most simple and kinda dirty option is to `git clone` this repo in your Projects directory,cd into it and `guix package -L guix -f guix.scm`. Then you'll have it installed. 

`clojureism` depends on `srfi-125` (which depends on `srfi-126`). Both of them are into `guix/packages/srfi` repo of this project. I've send `srfi-126` [into the guix itself](https://patchwise.org/71141) but it's still on review. As soon as it will be accepted I'll send srfi-125. Then it will be possible to pack `clojureism` in guix `(gnu packages guile-xyz)`. 

See `tests` on usage.

**Comment by shegeley** [comment]
See this commit of my other project to check how it could be packaged with `git-fetch` method

https://github.com/shegeley/hatis/commit/14f2e85c71e87c877c1ba3f25caa99f5bcbb664d
